### ISSUE TITLE
multiple use references

### ISSUE THREAD

**Issue by Spica2** [coma/gulp-svg-icons#3]
Is there a way to include symbols without nessecarly having the <icon-trophy class="red"> referene in the markup. I try to get a svg with two use references, how to include the two symbols

**Comment by coma** [comment]
I have to add an option for this.

**Comment by Spica2** [comment]
Simply a comment like `<!-- icon-trophy class="red" -->` would help. This comment can then be deleted and the symbol inserted. This could also help when responsive svgs with custom svg attributes are needed.

**Comment by coma** [comment]
Hey buddy,

I've been enjoying some holidays, but finally a new injectOnlyUsedIcons is available, check it out!

**Comment by Spica2** [comment]
Ah, thanks. Just checked it out. Very usefull. But as I have a large icons set in one dir for different pages all using different icons I need the only-used-icons-injection feature. Meanwhile I used the processhtml with  to remove the already replaced icons, that I just need for a multiple use link at a different svg. I hoped to leave that processhtml out.
